name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  run-pnpm:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js (version 22) and PNPM (version 9)
      - name: Setup Node.js and PNPM
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Enable PNPM
        run: |
          corepack enable

      # 3. Install dependencies using PNPM
      - name: Install dependencies
        run: pnpm install

      # 4. Run the application
      - name: Start the application
        run: pnpm start
